# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c5e5869870e18cbcff90c11620948a9d1d8ca7507fc7e497e3a02cb842a1d241f3f94f7d01b1fa3cb3f98841e3f6689e5852b7a2952131336c13ade0bf75c4d

test:
  secret_key_base: 98f46f6a26e65a821252af233324d4040082fe5c31afd17886b6f14bd3024d6bf09ab19e65691b83dda887b7c9876cff3071d1fa76de28f08fbc615497c93aac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
